-- Convert every cuid string primary key to a sequential integer, preserving all
-- rows and remapping every foreign key + soft (unconstrained) id reference.
-- Postgres runs this migration inside a transaction (Prisma default), so a
-- failure rolls the whole thing back — the table is never left half-migrated.
--
-- New ids are assigned per table by creation order (created_at, then old id),
-- so the lowest ids belong to the oldest rows.

-- ============================================================
-- PHASE 0 — drop every foreign-key constraint
-- ============================================================
ALTER TABLE "nanny_profiles" DROP CONSTRAINT IF EXISTS "nanny_profiles_user_id_fkey";
ALTER TABLE "nanny_skills" DROP CONSTRAINT IF EXISTS "nanny_skills_nanny_profile_id_fkey";
ALTER TABLE "nanny_skills" DROP CONSTRAINT IF EXISTS "nanny_skills_skill_id_fkey";
ALTER TABLE "promo_code_redemptions" DROP CONSTRAINT IF EXISTS "promo_code_redemptions_promo_code_id_fkey";
ALTER TABLE "promo_code_redemptions" DROP CONSTRAINT IF EXISTS "promo_code_redemptions_user_id_fkey";
ALTER TABLE "reward_wallets" DROP CONSTRAINT IF EXISTS "reward_wallets_user_id_fkey";
ALTER TABLE "reward_ledger_entries" DROP CONSTRAINT IF EXISTS "reward_ledger_entries_wallet_id_fkey";
ALTER TABLE "reward_ledger_entries" DROP CONSTRAINT IF EXISTS "reward_ledger_entries_user_id_fkey";
ALTER TABLE "reward_ledger_entries" DROP CONSTRAINT IF EXISTS "reward_ledger_entries_admin_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_mother_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_nanny_profile_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_promo_code_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_admin_approved_by_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_admin_action_by_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_cancelled_by_id_fkey";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_replacement_for_booking_id_fkey";
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_booking_id_fkey";
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_mother_id_fkey";
ALTER TABLE "reviews" DROP CONSTRAINT IF EXISTS "reviews_booking_id_fkey";
ALTER TABLE "reviews" DROP CONSTRAINT IF EXISTS "reviews_nanny_profile_id_fkey";
ALTER TABLE "reviews" DROP CONSTRAINT IF EXISTS "reviews_mother_id_fkey";
ALTER TABLE "care_logs" DROP CONSTRAINT IF EXISTS "care_logs_booking_id_fkey";
ALTER TABLE "care_logs" DROP CONSTRAINT IF EXISTS "care_logs_nanny_profile_id_fkey";
ALTER TABLE "community_posts" DROP CONSTRAINT IF EXISTS "community_posts_author_id_fkey";
ALTER TABLE "post_likes" DROP CONSTRAINT IF EXISTS "post_likes_post_id_fkey";
ALTER TABLE "post_likes" DROP CONSTRAINT IF EXISTS "post_likes_user_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_post_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_author_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_parent_comment_id_fkey";
ALTER TABLE "comment_likes" DROP CONSTRAINT IF EXISTS "comment_likes_comment_id_fkey";
ALTER TABLE "comment_likes" DROP CONSTRAINT IF EXISTS "comment_likes_user_id_fkey";
ALTER TABLE "event_rsvps" DROP CONSTRAINT IF EXISTS "event_rsvps_post_id_fkey";
ALTER TABLE "event_rsvps" DROP CONSTRAINT IF EXISTS "event_rsvps_user_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT IF EXISTS "conversations_community_post_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT IF EXISTS "conversations_initiator_id_fkey";
ALTER TABLE "conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_conversation_id_fkey";
ALTER TABLE "conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_user_id_fkey";
ALTER TABLE "messages" DROP CONSTRAINT IF EXISTS "messages_conversation_id_fkey";
ALTER TABLE "messages" DROP CONSTRAINT IF EXISTS "messages_sender_id_fkey";
ALTER TABLE "notifications" DROP CONSTRAINT IF EXISTS "notifications_user_id_fkey";
ALTER TABLE "device_tokens" DROP CONSTRAINT IF EXISTS "device_tokens_user_id_fkey";
ALTER TABLE "cameras" DROP CONSTRAINT IF EXISTS "cameras_nanny_user_id_fkey";

-- ============================================================
-- PHASE 1 — add integer id columns, numbered by creation order
-- ============================================================
ALTER TABLE "users" ADD COLUMN "_id_int" INTEGER;
UPDATE "users" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "users") s WHERE t."id" = s."id";
ALTER TABLE "nanny_profiles" ADD COLUMN "_id_int" INTEGER;
UPDATE "nanny_profiles" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "nanny_profiles") s WHERE t."id" = s."id";
ALTER TABLE "skills" ADD COLUMN "_id_int" INTEGER;
UPDATE "skills" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "skills") s WHERE t."id" = s."id";
ALTER TABLE "nanny_skills" ADD COLUMN "_id_int" INTEGER;
UPDATE "nanny_skills" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "nanny_skills") s WHERE t."id" = s."id";
ALTER TABLE "app_settings" ADD COLUMN "_id_int" INTEGER;
UPDATE "app_settings" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "app_settings") s WHERE t."id" = s."id";
ALTER TABLE "duration_multiplier_rules" ADD COLUMN "_id_int" INTEGER;
UPDATE "duration_multiplier_rules" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "duration_multiplier_rules") s WHERE t."id" = s."id";
ALTER TABLE "promo_codes" ADD COLUMN "_id_int" INTEGER;
UPDATE "promo_codes" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "promo_codes") s WHERE t."id" = s."id";
ALTER TABLE "promo_code_redemptions" ADD COLUMN "_id_int" INTEGER;
UPDATE "promo_code_redemptions" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "promo_code_redemptions") s WHERE t."id" = s."id";
ALTER TABLE "reward_config" ADD COLUMN "_id_int" INTEGER;
UPDATE "reward_config" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "reward_config") s WHERE t."id" = s."id";
ALTER TABLE "reward_wallets" ADD COLUMN "_id_int" INTEGER;
UPDATE "reward_wallets" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "reward_wallets") s WHERE t."id" = s."id";
ALTER TABLE "reward_ledger_entries" ADD COLUMN "_id_int" INTEGER;
UPDATE "reward_ledger_entries" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "reward_ledger_entries") s WHERE t."id" = s."id";
ALTER TABLE "bookings" ADD COLUMN "_id_int" INTEGER;
UPDATE "bookings" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "bookings") s WHERE t."id" = s."id";
ALTER TABLE "payments" ADD COLUMN "_id_int" INTEGER;
UPDATE "payments" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "payments") s WHERE t."id" = s."id";
ALTER TABLE "reviews" ADD COLUMN "_id_int" INTEGER;
UPDATE "reviews" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "reviews") s WHERE t."id" = s."id";
ALTER TABLE "care_logs" ADD COLUMN "_id_int" INTEGER;
UPDATE "care_logs" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "care_logs") s WHERE t."id" = s."id";
ALTER TABLE "community_posts" ADD COLUMN "_id_int" INTEGER;
UPDATE "community_posts" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "community_posts") s WHERE t."id" = s."id";
ALTER TABLE "post_likes" ADD COLUMN "_id_int" INTEGER;
UPDATE "post_likes" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "post_likes") s WHERE t."id" = s."id";
ALTER TABLE "comments" ADD COLUMN "_id_int" INTEGER;
UPDATE "comments" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "comments") s WHERE t."id" = s."id";
ALTER TABLE "comment_likes" ADD COLUMN "_id_int" INTEGER;
UPDATE "comment_likes" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "comment_likes") s WHERE t."id" = s."id";
ALTER TABLE "event_rsvps" ADD COLUMN "_id_int" INTEGER;
UPDATE "event_rsvps" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "event_rsvps") s WHERE t."id" = s."id";
ALTER TABLE "conversations" ADD COLUMN "_id_int" INTEGER;
UPDATE "conversations" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "conversations") s WHERE t."id" = s."id";
ALTER TABLE "conversation_participants" ADD COLUMN "_id_int" INTEGER;
UPDATE "conversation_participants" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "conversation_participants") s WHERE t."id" = s."id";
ALTER TABLE "messages" ADD COLUMN "_id_int" INTEGER;
UPDATE "messages" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "messages") s WHERE t."id" = s."id";
ALTER TABLE "notifications" ADD COLUMN "_id_int" INTEGER;
UPDATE "notifications" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "notifications") s WHERE t."id" = s."id";
ALTER TABLE "device_tokens" ADD COLUMN "_id_int" INTEGER;
UPDATE "device_tokens" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "device_tokens") s WHERE t."id" = s."id";
ALTER TABLE "cameras" ADD COLUMN "_id_int" INTEGER;
UPDATE "cameras" t SET "_id_int" = s.rn FROM (SELECT "id", row_number() OVER (ORDER BY "created_at" ASC, "id" ASC) AS rn FROM "cameras") s WHERE t."id" = s."id";

-- ============================================================
-- PHASE 2 — add integer FK columns, mapped from parents' new ids
-- ============================================================
ALTER TABLE "nanny_profiles" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "nanny_profiles" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "nanny_skills" ADD COLUMN "_nanny_profile_id_int" INTEGER;
UPDATE "nanny_skills" c SET "_nanny_profile_id_int" = p."_id_int" FROM "nanny_profiles" p WHERE c."nanny_profile_id" = p."id";
ALTER TABLE "nanny_skills" ADD COLUMN "_skill_id_int" INTEGER;
UPDATE "nanny_skills" c SET "_skill_id_int" = p."_id_int" FROM "skills" p WHERE c."skill_id" = p."id";
ALTER TABLE "promo_code_redemptions" ADD COLUMN "_promo_code_id_int" INTEGER;
UPDATE "promo_code_redemptions" c SET "_promo_code_id_int" = p."_id_int" FROM "promo_codes" p WHERE c."promo_code_id" = p."id";
ALTER TABLE "promo_code_redemptions" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "promo_code_redemptions" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "reward_wallets" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "reward_wallets" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "reward_ledger_entries" ADD COLUMN "_wallet_id_int" INTEGER;
UPDATE "reward_ledger_entries" c SET "_wallet_id_int" = p."_id_int" FROM "reward_wallets" p WHERE c."wallet_id" = p."id";
ALTER TABLE "reward_ledger_entries" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "reward_ledger_entries" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "reward_ledger_entries" ADD COLUMN "_admin_id_int" INTEGER;
UPDATE "reward_ledger_entries" c SET "_admin_id_int" = p."_id_int" FROM "users" p WHERE c."admin_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_mother_id_int" INTEGER;
UPDATE "bookings" c SET "_mother_id_int" = p."_id_int" FROM "users" p WHERE c."mother_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_nanny_profile_id_int" INTEGER;
UPDATE "bookings" c SET "_nanny_profile_id_int" = p."_id_int" FROM "nanny_profiles" p WHERE c."nanny_profile_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_promo_code_id_int" INTEGER;
UPDATE "bookings" c SET "_promo_code_id_int" = p."_id_int" FROM "promo_codes" p WHERE c."promo_code_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_admin_approved_by_id_int" INTEGER;
UPDATE "bookings" c SET "_admin_approved_by_id_int" = p."_id_int" FROM "users" p WHERE c."admin_approved_by_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_admin_action_by_id_int" INTEGER;
UPDATE "bookings" c SET "_admin_action_by_id_int" = p."_id_int" FROM "users" p WHERE c."admin_action_by_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_cancelled_by_id_int" INTEGER;
UPDATE "bookings" c SET "_cancelled_by_id_int" = p."_id_int" FROM "users" p WHERE c."cancelled_by_id" = p."id";
ALTER TABLE "bookings" ADD COLUMN "_replacement_for_booking_id_int" INTEGER;
UPDATE "bookings" c SET "_replacement_for_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."replacement_for_booking_id" = p."id";
ALTER TABLE "payments" ADD COLUMN "_booking_id_int" INTEGER;
UPDATE "payments" c SET "_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."booking_id" = p."id";
ALTER TABLE "payments" ADD COLUMN "_mother_id_int" INTEGER;
UPDATE "payments" c SET "_mother_id_int" = p."_id_int" FROM "users" p WHERE c."mother_id" = p."id";
ALTER TABLE "reviews" ADD COLUMN "_booking_id_int" INTEGER;
UPDATE "reviews" c SET "_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."booking_id" = p."id";
ALTER TABLE "reviews" ADD COLUMN "_nanny_profile_id_int" INTEGER;
UPDATE "reviews" c SET "_nanny_profile_id_int" = p."_id_int" FROM "nanny_profiles" p WHERE c."nanny_profile_id" = p."id";
ALTER TABLE "reviews" ADD COLUMN "_mother_id_int" INTEGER;
UPDATE "reviews" c SET "_mother_id_int" = p."_id_int" FROM "users" p WHERE c."mother_id" = p."id";
ALTER TABLE "care_logs" ADD COLUMN "_booking_id_int" INTEGER;
UPDATE "care_logs" c SET "_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."booking_id" = p."id";
ALTER TABLE "care_logs" ADD COLUMN "_nanny_profile_id_int" INTEGER;
UPDATE "care_logs" c SET "_nanny_profile_id_int" = p."_id_int" FROM "nanny_profiles" p WHERE c."nanny_profile_id" = p."id";
ALTER TABLE "community_posts" ADD COLUMN "_author_id_int" INTEGER;
UPDATE "community_posts" c SET "_author_id_int" = p."_id_int" FROM "users" p WHERE c."author_id" = p."id";
ALTER TABLE "post_likes" ADD COLUMN "_post_id_int" INTEGER;
UPDATE "post_likes" c SET "_post_id_int" = p."_id_int" FROM "community_posts" p WHERE c."post_id" = p."id";
ALTER TABLE "post_likes" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "post_likes" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "comments" ADD COLUMN "_post_id_int" INTEGER;
UPDATE "comments" c SET "_post_id_int" = p."_id_int" FROM "community_posts" p WHERE c."post_id" = p."id";
ALTER TABLE "comments" ADD COLUMN "_author_id_int" INTEGER;
UPDATE "comments" c SET "_author_id_int" = p."_id_int" FROM "users" p WHERE c."author_id" = p."id";
ALTER TABLE "comments" ADD COLUMN "_parent_comment_id_int" INTEGER;
UPDATE "comments" c SET "_parent_comment_id_int" = p."_id_int" FROM "comments" p WHERE c."parent_comment_id" = p."id";
ALTER TABLE "comment_likes" ADD COLUMN "_comment_id_int" INTEGER;
UPDATE "comment_likes" c SET "_comment_id_int" = p."_id_int" FROM "comments" p WHERE c."comment_id" = p."id";
ALTER TABLE "comment_likes" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "comment_likes" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "event_rsvps" ADD COLUMN "_post_id_int" INTEGER;
UPDATE "event_rsvps" c SET "_post_id_int" = p."_id_int" FROM "community_posts" p WHERE c."post_id" = p."id";
ALTER TABLE "event_rsvps" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "event_rsvps" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "conversations" ADD COLUMN "_community_post_id_int" INTEGER;
UPDATE "conversations" c SET "_community_post_id_int" = p."_id_int" FROM "community_posts" p WHERE c."community_post_id" = p."id";
ALTER TABLE "conversations" ADD COLUMN "_initiator_id_int" INTEGER;
UPDATE "conversations" c SET "_initiator_id_int" = p."_id_int" FROM "users" p WHERE c."initiator_id" = p."id";
ALTER TABLE "conversation_participants" ADD COLUMN "_conversation_id_int" INTEGER;
UPDATE "conversation_participants" c SET "_conversation_id_int" = p."_id_int" FROM "conversations" p WHERE c."conversation_id" = p."id";
ALTER TABLE "conversation_participants" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "conversation_participants" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "messages" ADD COLUMN "_conversation_id_int" INTEGER;
UPDATE "messages" c SET "_conversation_id_int" = p."_id_int" FROM "conversations" p WHERE c."conversation_id" = p."id";
ALTER TABLE "messages" ADD COLUMN "_sender_id_int" INTEGER;
UPDATE "messages" c SET "_sender_id_int" = p."_id_int" FROM "users" p WHERE c."sender_id" = p."id";
ALTER TABLE "notifications" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "notifications" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "device_tokens" ADD COLUMN "_user_id_int" INTEGER;
UPDATE "device_tokens" c SET "_user_id_int" = p."_id_int" FROM "users" p WHERE c."user_id" = p."id";
ALTER TABLE "cameras" ADD COLUMN "_nanny_user_id_int" INTEGER;
UPDATE "cameras" c SET "_nanny_user_id_int" = p."_id_int" FROM "users" p WHERE c."nanny_user_id" = p."id";
ALTER TABLE "promo_code_redemptions" ADD COLUMN "_booking_id_int" INTEGER;
UPDATE "promo_code_redemptions" c SET "_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."booking_id" = p."id";
ALTER TABLE "reward_ledger_entries" ADD COLUMN "_booking_id_int" INTEGER;
UPDATE "reward_ledger_entries" c SET "_booking_id_int" = p."_id_int" FROM "bookings" p WHERE c."booking_id" = p."id";
ALTER TABLE "notifications" ADD COLUMN "_reference_id_int" INTEGER;
UPDATE "notifications" c SET "_reference_id_int" = p."_id_int" FROM "bookings" p WHERE c."reference_id" = p."id" AND c."reference_type"::text = 'BOOKING';
UPDATE "notifications" c SET "_reference_id_int" = p."_id_int" FROM "conversations" p WHERE c."reference_id" = p."id" AND c."reference_type"::text = 'CONVERSATION';

-- ============================================================
-- PHASE 3 — drop old text columns, rename integer columns into place
-- ============================================================
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_pkey";
ALTER TABLE "users" DROP COLUMN "id";
ALTER TABLE "users" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "nanny_profiles" DROP CONSTRAINT IF EXISTS "nanny_profiles_pkey";
ALTER TABLE "nanny_profiles" DROP COLUMN "id";
ALTER TABLE "nanny_profiles" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "nanny_profiles" DROP COLUMN "user_id";
ALTER TABLE "nanny_profiles" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "skills" DROP CONSTRAINT IF EXISTS "skills_pkey";
ALTER TABLE "skills" DROP COLUMN "id";
ALTER TABLE "skills" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "nanny_skills" DROP CONSTRAINT IF EXISTS "nanny_skills_pkey";
ALTER TABLE "nanny_skills" DROP COLUMN "id";
ALTER TABLE "nanny_skills" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "nanny_skills" DROP COLUMN "nanny_profile_id";
ALTER TABLE "nanny_skills" RENAME COLUMN "_nanny_profile_id_int" TO "nanny_profile_id";
ALTER TABLE "nanny_skills" DROP COLUMN "skill_id";
ALTER TABLE "nanny_skills" RENAME COLUMN "_skill_id_int" TO "skill_id";
ALTER TABLE "app_settings" DROP CONSTRAINT IF EXISTS "app_settings_pkey";
ALTER TABLE "app_settings" DROP COLUMN "id";
ALTER TABLE "app_settings" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "duration_multiplier_rules" DROP CONSTRAINT IF EXISTS "duration_multiplier_rules_pkey";
ALTER TABLE "duration_multiplier_rules" DROP COLUMN "id";
ALTER TABLE "duration_multiplier_rules" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "promo_codes" DROP CONSTRAINT IF EXISTS "promo_codes_pkey";
ALTER TABLE "promo_codes" DROP COLUMN "id";
ALTER TABLE "promo_codes" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "promo_code_redemptions" DROP CONSTRAINT IF EXISTS "promo_code_redemptions_pkey";
ALTER TABLE "promo_code_redemptions" DROP COLUMN "id";
ALTER TABLE "promo_code_redemptions" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "promo_code_redemptions" DROP COLUMN "promo_code_id";
ALTER TABLE "promo_code_redemptions" RENAME COLUMN "_promo_code_id_int" TO "promo_code_id";
ALTER TABLE "promo_code_redemptions" DROP COLUMN "user_id";
ALTER TABLE "promo_code_redemptions" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "promo_code_redemptions" DROP COLUMN "booking_id";
ALTER TABLE "promo_code_redemptions" RENAME COLUMN "_booking_id_int" TO "booking_id";
ALTER TABLE "reward_config" DROP CONSTRAINT IF EXISTS "reward_config_pkey";
ALTER TABLE "reward_config" DROP COLUMN "id";
ALTER TABLE "reward_config" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "reward_wallets" DROP CONSTRAINT IF EXISTS "reward_wallets_pkey";
ALTER TABLE "reward_wallets" DROP COLUMN "id";
ALTER TABLE "reward_wallets" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "reward_wallets" DROP COLUMN "user_id";
ALTER TABLE "reward_wallets" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "reward_ledger_entries" DROP CONSTRAINT IF EXISTS "reward_ledger_entries_pkey";
ALTER TABLE "reward_ledger_entries" DROP COLUMN "id";
ALTER TABLE "reward_ledger_entries" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "reward_ledger_entries" DROP COLUMN "wallet_id";
ALTER TABLE "reward_ledger_entries" RENAME COLUMN "_wallet_id_int" TO "wallet_id";
ALTER TABLE "reward_ledger_entries" DROP COLUMN "user_id";
ALTER TABLE "reward_ledger_entries" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "reward_ledger_entries" DROP COLUMN "admin_id";
ALTER TABLE "reward_ledger_entries" RENAME COLUMN "_admin_id_int" TO "admin_id";
ALTER TABLE "reward_ledger_entries" DROP COLUMN "booking_id";
ALTER TABLE "reward_ledger_entries" RENAME COLUMN "_booking_id_int" TO "booking_id";
ALTER TABLE "bookings" DROP CONSTRAINT IF EXISTS "bookings_pkey";
ALTER TABLE "bookings" DROP COLUMN "id";
ALTER TABLE "bookings" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "bookings" DROP COLUMN "mother_id";
ALTER TABLE "bookings" RENAME COLUMN "_mother_id_int" TO "mother_id";
ALTER TABLE "bookings" DROP COLUMN "nanny_profile_id";
ALTER TABLE "bookings" RENAME COLUMN "_nanny_profile_id_int" TO "nanny_profile_id";
ALTER TABLE "bookings" DROP COLUMN "promo_code_id";
ALTER TABLE "bookings" RENAME COLUMN "_promo_code_id_int" TO "promo_code_id";
ALTER TABLE "bookings" DROP COLUMN "admin_approved_by_id";
ALTER TABLE "bookings" RENAME COLUMN "_admin_approved_by_id_int" TO "admin_approved_by_id";
ALTER TABLE "bookings" DROP COLUMN "admin_action_by_id";
ALTER TABLE "bookings" RENAME COLUMN "_admin_action_by_id_int" TO "admin_action_by_id";
ALTER TABLE "bookings" DROP COLUMN "cancelled_by_id";
ALTER TABLE "bookings" RENAME COLUMN "_cancelled_by_id_int" TO "cancelled_by_id";
ALTER TABLE "bookings" DROP COLUMN "replacement_for_booking_id";
ALTER TABLE "bookings" RENAME COLUMN "_replacement_for_booking_id_int" TO "replacement_for_booking_id";
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_pkey";
ALTER TABLE "payments" DROP COLUMN "id";
ALTER TABLE "payments" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "payments" DROP COLUMN "booking_id";
ALTER TABLE "payments" RENAME COLUMN "_booking_id_int" TO "booking_id";
ALTER TABLE "payments" DROP COLUMN "mother_id";
ALTER TABLE "payments" RENAME COLUMN "_mother_id_int" TO "mother_id";
ALTER TABLE "reviews" DROP CONSTRAINT IF EXISTS "reviews_pkey";
ALTER TABLE "reviews" DROP COLUMN "id";
ALTER TABLE "reviews" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "reviews" DROP COLUMN "booking_id";
ALTER TABLE "reviews" RENAME COLUMN "_booking_id_int" TO "booking_id";
ALTER TABLE "reviews" DROP COLUMN "nanny_profile_id";
ALTER TABLE "reviews" RENAME COLUMN "_nanny_profile_id_int" TO "nanny_profile_id";
ALTER TABLE "reviews" DROP COLUMN "mother_id";
ALTER TABLE "reviews" RENAME COLUMN "_mother_id_int" TO "mother_id";
ALTER TABLE "care_logs" DROP CONSTRAINT IF EXISTS "care_logs_pkey";
ALTER TABLE "care_logs" DROP COLUMN "id";
ALTER TABLE "care_logs" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "care_logs" DROP COLUMN "booking_id";
ALTER TABLE "care_logs" RENAME COLUMN "_booking_id_int" TO "booking_id";
ALTER TABLE "care_logs" DROP COLUMN "nanny_profile_id";
ALTER TABLE "care_logs" RENAME COLUMN "_nanny_profile_id_int" TO "nanny_profile_id";
ALTER TABLE "community_posts" DROP CONSTRAINT IF EXISTS "community_posts_pkey";
ALTER TABLE "community_posts" DROP COLUMN "id";
ALTER TABLE "community_posts" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "community_posts" DROP COLUMN "author_id";
ALTER TABLE "community_posts" RENAME COLUMN "_author_id_int" TO "author_id";
ALTER TABLE "post_likes" DROP CONSTRAINT IF EXISTS "post_likes_pkey";
ALTER TABLE "post_likes" DROP COLUMN "id";
ALTER TABLE "post_likes" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "post_likes" DROP COLUMN "post_id";
ALTER TABLE "post_likes" RENAME COLUMN "_post_id_int" TO "post_id";
ALTER TABLE "post_likes" DROP COLUMN "user_id";
ALTER TABLE "post_likes" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_pkey";
ALTER TABLE "comments" DROP COLUMN "id";
ALTER TABLE "comments" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "comments" DROP COLUMN "post_id";
ALTER TABLE "comments" RENAME COLUMN "_post_id_int" TO "post_id";
ALTER TABLE "comments" DROP COLUMN "author_id";
ALTER TABLE "comments" RENAME COLUMN "_author_id_int" TO "author_id";
ALTER TABLE "comments" DROP COLUMN "parent_comment_id";
ALTER TABLE "comments" RENAME COLUMN "_parent_comment_id_int" TO "parent_comment_id";
ALTER TABLE "comment_likes" DROP CONSTRAINT IF EXISTS "comment_likes_pkey";
ALTER TABLE "comment_likes" DROP COLUMN "id";
ALTER TABLE "comment_likes" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "comment_likes" DROP COLUMN "comment_id";
ALTER TABLE "comment_likes" RENAME COLUMN "_comment_id_int" TO "comment_id";
ALTER TABLE "comment_likes" DROP COLUMN "user_id";
ALTER TABLE "comment_likes" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "event_rsvps" DROP CONSTRAINT IF EXISTS "event_rsvps_pkey";
ALTER TABLE "event_rsvps" DROP COLUMN "id";
ALTER TABLE "event_rsvps" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "event_rsvps" DROP COLUMN "post_id";
ALTER TABLE "event_rsvps" RENAME COLUMN "_post_id_int" TO "post_id";
ALTER TABLE "event_rsvps" DROP COLUMN "user_id";
ALTER TABLE "event_rsvps" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "conversations" DROP CONSTRAINT IF EXISTS "conversations_pkey";
ALTER TABLE "conversations" DROP COLUMN "id";
ALTER TABLE "conversations" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "conversations" DROP COLUMN "community_post_id";
ALTER TABLE "conversations" RENAME COLUMN "_community_post_id_int" TO "community_post_id";
ALTER TABLE "conversations" DROP COLUMN "initiator_id";
ALTER TABLE "conversations" RENAME COLUMN "_initiator_id_int" TO "initiator_id";
ALTER TABLE "conversation_participants" DROP CONSTRAINT IF EXISTS "conversation_participants_pkey";
ALTER TABLE "conversation_participants" DROP COLUMN "id";
ALTER TABLE "conversation_participants" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "conversation_participants" DROP COLUMN "conversation_id";
ALTER TABLE "conversation_participants" RENAME COLUMN "_conversation_id_int" TO "conversation_id";
ALTER TABLE "conversation_participants" DROP COLUMN "user_id";
ALTER TABLE "conversation_participants" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "messages" DROP CONSTRAINT IF EXISTS "messages_pkey";
ALTER TABLE "messages" DROP COLUMN "id";
ALTER TABLE "messages" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "messages" DROP COLUMN "conversation_id";
ALTER TABLE "messages" RENAME COLUMN "_conversation_id_int" TO "conversation_id";
ALTER TABLE "messages" DROP COLUMN "sender_id";
ALTER TABLE "messages" RENAME COLUMN "_sender_id_int" TO "sender_id";
ALTER TABLE "notifications" DROP CONSTRAINT IF EXISTS "notifications_pkey";
ALTER TABLE "notifications" DROP COLUMN "id";
ALTER TABLE "notifications" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "notifications" DROP COLUMN "user_id";
ALTER TABLE "notifications" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "notifications" DROP COLUMN "reference_id";
ALTER TABLE "notifications" RENAME COLUMN "_reference_id_int" TO "reference_id";
ALTER TABLE "device_tokens" DROP CONSTRAINT IF EXISTS "device_tokens_pkey";
ALTER TABLE "device_tokens" DROP COLUMN "id";
ALTER TABLE "device_tokens" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "device_tokens" DROP COLUMN "user_id";
ALTER TABLE "device_tokens" RENAME COLUMN "_user_id_int" TO "user_id";
ALTER TABLE "cameras" DROP CONSTRAINT IF EXISTS "cameras_pkey";
ALTER TABLE "cameras" DROP COLUMN "id";
ALTER TABLE "cameras" RENAME COLUMN "_id_int" TO "id";
ALTER TABLE "cameras" DROP COLUMN "nanny_user_id";
ALTER TABLE "cameras" RENAME COLUMN "_nanny_user_id_int" TO "nanny_user_id";

-- ============================================================
-- PHASE 4 — primary keys, autoincrement sequences, NOT NULL, FKs, indexes
-- ============================================================
ALTER TABLE "users" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "users_id_seq" AS integer;
ALTER SEQUENCE "users_id_seq" OWNED BY "users"."id";
SELECT setval('"users_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "users"), false);
ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT nextval('"users_id_seq"');
ALTER TABLE "nanny_profiles" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "nanny_profiles" ADD CONSTRAINT "nanny_profiles_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "nanny_profiles_id_seq" AS integer;
ALTER SEQUENCE "nanny_profiles_id_seq" OWNED BY "nanny_profiles"."id";
SELECT setval('"nanny_profiles_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "nanny_profiles"), false);
ALTER TABLE "nanny_profiles" ALTER COLUMN "id" SET DEFAULT nextval('"nanny_profiles_id_seq"');
ALTER TABLE "skills" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "skills" ADD CONSTRAINT "skills_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "skills_id_seq" AS integer;
ALTER SEQUENCE "skills_id_seq" OWNED BY "skills"."id";
SELECT setval('"skills_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "skills"), false);
ALTER TABLE "skills" ALTER COLUMN "id" SET DEFAULT nextval('"skills_id_seq"');
ALTER TABLE "nanny_skills" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "nanny_skills" ADD CONSTRAINT "nanny_skills_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "nanny_skills_id_seq" AS integer;
ALTER SEQUENCE "nanny_skills_id_seq" OWNED BY "nanny_skills"."id";
SELECT setval('"nanny_skills_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "nanny_skills"), false);
ALTER TABLE "nanny_skills" ALTER COLUMN "id" SET DEFAULT nextval('"nanny_skills_id_seq"');
ALTER TABLE "app_settings" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "app_settings" ADD CONSTRAINT "app_settings_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "app_settings_id_seq" AS integer;
ALTER SEQUENCE "app_settings_id_seq" OWNED BY "app_settings"."id";
SELECT setval('"app_settings_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "app_settings"), false);
ALTER TABLE "app_settings" ALTER COLUMN "id" SET DEFAULT nextval('"app_settings_id_seq"');
ALTER TABLE "duration_multiplier_rules" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "duration_multiplier_rules" ADD CONSTRAINT "duration_multiplier_rules_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "duration_multiplier_rules_id_seq" AS integer;
ALTER SEQUENCE "duration_multiplier_rules_id_seq" OWNED BY "duration_multiplier_rules"."id";
SELECT setval('"duration_multiplier_rules_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "duration_multiplier_rules"), false);
ALTER TABLE "duration_multiplier_rules" ALTER COLUMN "id" SET DEFAULT nextval('"duration_multiplier_rules_id_seq"');
ALTER TABLE "promo_codes" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "promo_codes" ADD CONSTRAINT "promo_codes_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "promo_codes_id_seq" AS integer;
ALTER SEQUENCE "promo_codes_id_seq" OWNED BY "promo_codes"."id";
SELECT setval('"promo_codes_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "promo_codes"), false);
ALTER TABLE "promo_codes" ALTER COLUMN "id" SET DEFAULT nextval('"promo_codes_id_seq"');
ALTER TABLE "promo_code_redemptions" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "promo_code_redemptions" ADD CONSTRAINT "promo_code_redemptions_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "promo_code_redemptions_id_seq" AS integer;
ALTER SEQUENCE "promo_code_redemptions_id_seq" OWNED BY "promo_code_redemptions"."id";
SELECT setval('"promo_code_redemptions_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "promo_code_redemptions"), false);
ALTER TABLE "promo_code_redemptions" ALTER COLUMN "id" SET DEFAULT nextval('"promo_code_redemptions_id_seq"');
ALTER TABLE "reward_config" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "reward_config" ADD CONSTRAINT "reward_config_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "reward_config_id_seq" AS integer;
ALTER SEQUENCE "reward_config_id_seq" OWNED BY "reward_config"."id";
SELECT setval('"reward_config_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "reward_config"), false);
ALTER TABLE "reward_config" ALTER COLUMN "id" SET DEFAULT nextval('"reward_config_id_seq"');
ALTER TABLE "reward_wallets" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "reward_wallets" ADD CONSTRAINT "reward_wallets_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "reward_wallets_id_seq" AS integer;
ALTER SEQUENCE "reward_wallets_id_seq" OWNED BY "reward_wallets"."id";
SELECT setval('"reward_wallets_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "reward_wallets"), false);
ALTER TABLE "reward_wallets" ALTER COLUMN "id" SET DEFAULT nextval('"reward_wallets_id_seq"');
ALTER TABLE "reward_ledger_entries" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "reward_ledger_entries" ADD CONSTRAINT "reward_ledger_entries_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "reward_ledger_entries_id_seq" AS integer;
ALTER SEQUENCE "reward_ledger_entries_id_seq" OWNED BY "reward_ledger_entries"."id";
SELECT setval('"reward_ledger_entries_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "reward_ledger_entries"), false);
ALTER TABLE "reward_ledger_entries" ALTER COLUMN "id" SET DEFAULT nextval('"reward_ledger_entries_id_seq"');
ALTER TABLE "bookings" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "bookings_id_seq" AS integer;
ALTER SEQUENCE "bookings_id_seq" OWNED BY "bookings"."id";
SELECT setval('"bookings_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "bookings"), false);
ALTER TABLE "bookings" ALTER COLUMN "id" SET DEFAULT nextval('"bookings_id_seq"');
ALTER TABLE "payments" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "payments" ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "payments_id_seq" AS integer;
ALTER SEQUENCE "payments_id_seq" OWNED BY "payments"."id";
SELECT setval('"payments_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "payments"), false);
ALTER TABLE "payments" ALTER COLUMN "id" SET DEFAULT nextval('"payments_id_seq"');
ALTER TABLE "reviews" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "reviews_id_seq" AS integer;
ALTER SEQUENCE "reviews_id_seq" OWNED BY "reviews"."id";
SELECT setval('"reviews_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "reviews"), false);
ALTER TABLE "reviews" ALTER COLUMN "id" SET DEFAULT nextval('"reviews_id_seq"');
ALTER TABLE "care_logs" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "care_logs" ADD CONSTRAINT "care_logs_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "care_logs_id_seq" AS integer;
ALTER SEQUENCE "care_logs_id_seq" OWNED BY "care_logs"."id";
SELECT setval('"care_logs_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "care_logs"), false);
ALTER TABLE "care_logs" ALTER COLUMN "id" SET DEFAULT nextval('"care_logs_id_seq"');
ALTER TABLE "community_posts" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "community_posts" ADD CONSTRAINT "community_posts_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "community_posts_id_seq" AS integer;
ALTER SEQUENCE "community_posts_id_seq" OWNED BY "community_posts"."id";
SELECT setval('"community_posts_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "community_posts"), false);
ALTER TABLE "community_posts" ALTER COLUMN "id" SET DEFAULT nextval('"community_posts_id_seq"');
ALTER TABLE "post_likes" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "post_likes_id_seq" AS integer;
ALTER SEQUENCE "post_likes_id_seq" OWNED BY "post_likes"."id";
SELECT setval('"post_likes_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "post_likes"), false);
ALTER TABLE "post_likes" ALTER COLUMN "id" SET DEFAULT nextval('"post_likes_id_seq"');
ALTER TABLE "comments" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "comments" ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "comments_id_seq" AS integer;
ALTER SEQUENCE "comments_id_seq" OWNED BY "comments"."id";
SELECT setval('"comments_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "comments"), false);
ALTER TABLE "comments" ALTER COLUMN "id" SET DEFAULT nextval('"comments_id_seq"');
ALTER TABLE "comment_likes" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "comment_likes" ADD CONSTRAINT "comment_likes_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "comment_likes_id_seq" AS integer;
ALTER SEQUENCE "comment_likes_id_seq" OWNED BY "comment_likes"."id";
SELECT setval('"comment_likes_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "comment_likes"), false);
ALTER TABLE "comment_likes" ALTER COLUMN "id" SET DEFAULT nextval('"comment_likes_id_seq"');
ALTER TABLE "event_rsvps" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "event_rsvps" ADD CONSTRAINT "event_rsvps_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "event_rsvps_id_seq" AS integer;
ALTER SEQUENCE "event_rsvps_id_seq" OWNED BY "event_rsvps"."id";
SELECT setval('"event_rsvps_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "event_rsvps"), false);
ALTER TABLE "event_rsvps" ALTER COLUMN "id" SET DEFAULT nextval('"event_rsvps_id_seq"');
ALTER TABLE "conversations" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "conversations_id_seq" AS integer;
ALTER SEQUENCE "conversations_id_seq" OWNED BY "conversations"."id";
SELECT setval('"conversations_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "conversations"), false);
ALTER TABLE "conversations" ALTER COLUMN "id" SET DEFAULT nextval('"conversations_id_seq"');
ALTER TABLE "conversation_participants" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "conversation_participants_id_seq" AS integer;
ALTER SEQUENCE "conversation_participants_id_seq" OWNED BY "conversation_participants"."id";
SELECT setval('"conversation_participants_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "conversation_participants"), false);
ALTER TABLE "conversation_participants" ALTER COLUMN "id" SET DEFAULT nextval('"conversation_participants_id_seq"');
ALTER TABLE "messages" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "messages_id_seq" AS integer;
ALTER SEQUENCE "messages_id_seq" OWNED BY "messages"."id";
SELECT setval('"messages_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "messages"), false);
ALTER TABLE "messages" ALTER COLUMN "id" SET DEFAULT nextval('"messages_id_seq"');
ALTER TABLE "notifications" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "notifications_id_seq" AS integer;
ALTER SEQUENCE "notifications_id_seq" OWNED BY "notifications"."id";
SELECT setval('"notifications_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "notifications"), false);
ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT nextval('"notifications_id_seq"');
ALTER TABLE "device_tokens" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "device_tokens" ADD CONSTRAINT "device_tokens_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "device_tokens_id_seq" AS integer;
ALTER SEQUENCE "device_tokens_id_seq" OWNED BY "device_tokens"."id";
SELECT setval('"device_tokens_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "device_tokens"), false);
ALTER TABLE "device_tokens" ALTER COLUMN "id" SET DEFAULT nextval('"device_tokens_id_seq"');
ALTER TABLE "cameras" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE "cameras" ADD CONSTRAINT "cameras_pkey" PRIMARY KEY ("id");
CREATE SEQUENCE IF NOT EXISTS "cameras_id_seq" AS integer;
ALTER SEQUENCE "cameras_id_seq" OWNED BY "cameras"."id";
SELECT setval('"cameras_id_seq"', (SELECT COALESCE(MAX("id"), 0) + 1 FROM "cameras"), false);
ALTER TABLE "cameras" ALTER COLUMN "id" SET DEFAULT nextval('"cameras_id_seq"');

ALTER TABLE "nanny_profiles" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "nanny_skills" ALTER COLUMN "nanny_profile_id" SET NOT NULL;
ALTER TABLE "nanny_skills" ALTER COLUMN "skill_id" SET NOT NULL;
ALTER TABLE "promo_code_redemptions" ALTER COLUMN "promo_code_id" SET NOT NULL;
ALTER TABLE "promo_code_redemptions" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "reward_wallets" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "reward_ledger_entries" ALTER COLUMN "wallet_id" SET NOT NULL;
ALTER TABLE "reward_ledger_entries" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "bookings" ALTER COLUMN "mother_id" SET NOT NULL;
ALTER TABLE "payments" ALTER COLUMN "booking_id" SET NOT NULL;
ALTER TABLE "payments" ALTER COLUMN "mother_id" SET NOT NULL;
ALTER TABLE "reviews" ALTER COLUMN "booking_id" SET NOT NULL;
ALTER TABLE "reviews" ALTER COLUMN "nanny_profile_id" SET NOT NULL;
ALTER TABLE "reviews" ALTER COLUMN "mother_id" SET NOT NULL;
ALTER TABLE "care_logs" ALTER COLUMN "booking_id" SET NOT NULL;
ALTER TABLE "care_logs" ALTER COLUMN "nanny_profile_id" SET NOT NULL;
ALTER TABLE "community_posts" ALTER COLUMN "author_id" SET NOT NULL;
ALTER TABLE "post_likes" ALTER COLUMN "post_id" SET NOT NULL;
ALTER TABLE "post_likes" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "comments" ALTER COLUMN "post_id" SET NOT NULL;
ALTER TABLE "comments" ALTER COLUMN "author_id" SET NOT NULL;
ALTER TABLE "comment_likes" ALTER COLUMN "comment_id" SET NOT NULL;
ALTER TABLE "comment_likes" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "event_rsvps" ALTER COLUMN "post_id" SET NOT NULL;
ALTER TABLE "event_rsvps" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "conversations" ALTER COLUMN "community_post_id" SET NOT NULL;
ALTER TABLE "conversations" ALTER COLUMN "initiator_id" SET NOT NULL;
ALTER TABLE "conversation_participants" ALTER COLUMN "conversation_id" SET NOT NULL;
ALTER TABLE "conversation_participants" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "messages" ALTER COLUMN "conversation_id" SET NOT NULL;
ALTER TABLE "messages" ALTER COLUMN "sender_id" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "user_id" SET NOT NULL;
ALTER TABLE "device_tokens" ALTER COLUMN "user_id" SET NOT NULL;

ALTER TABLE "nanny_profiles" ADD CONSTRAINT "nanny_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "nanny_skills" ADD CONSTRAINT "nanny_skills_nanny_profile_id_fkey" FOREIGN KEY ("nanny_profile_id") REFERENCES "nanny_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "nanny_skills" ADD CONSTRAINT "nanny_skills_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "promo_code_redemptions" ADD CONSTRAINT "promo_code_redemptions_promo_code_id_fkey" FOREIGN KEY ("promo_code_id") REFERENCES "promo_codes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "promo_code_redemptions" ADD CONSTRAINT "promo_code_redemptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reward_wallets" ADD CONSTRAINT "reward_wallets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reward_ledger_entries" ADD CONSTRAINT "reward_ledger_entries_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "reward_wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reward_ledger_entries" ADD CONSTRAINT "reward_ledger_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reward_ledger_entries" ADD CONSTRAINT "reward_ledger_entries_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_mother_id_fkey" FOREIGN KEY ("mother_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_nanny_profile_id_fkey" FOREIGN KEY ("nanny_profile_id") REFERENCES "nanny_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_promo_code_id_fkey" FOREIGN KEY ("promo_code_id") REFERENCES "promo_codes"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_admin_approved_by_id_fkey" FOREIGN KEY ("admin_approved_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_admin_action_by_id_fkey" FOREIGN KEY ("admin_action_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_cancelled_by_id_fkey" FOREIGN KEY ("cancelled_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_replacement_for_booking_id_fkey" FOREIGN KEY ("replacement_for_booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_mother_id_fkey" FOREIGN KEY ("mother_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_nanny_profile_id_fkey" FOREIGN KEY ("nanny_profile_id") REFERENCES "nanny_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_mother_id_fkey" FOREIGN KEY ("mother_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "care_logs" ADD CONSTRAINT "care_logs_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "care_logs" ADD CONSTRAINT "care_logs_nanny_profile_id_fkey" FOREIGN KEY ("nanny_profile_id") REFERENCES "nanny_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "community_posts" ADD CONSTRAINT "community_posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "community_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "community_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_parent_comment_id_fkey" FOREIGN KEY ("parent_comment_id") REFERENCES "comments"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "comment_likes" ADD CONSTRAINT "comment_likes_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comment_likes" ADD CONSTRAINT "comment_likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "event_rsvps" ADD CONSTRAINT "event_rsvps_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "community_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "event_rsvps" ADD CONSTRAINT "event_rsvps_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_community_post_id_fkey" FOREIGN KEY ("community_post_id") REFERENCES "community_posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_initiator_id_fkey" FOREIGN KEY ("initiator_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "device_tokens" ADD CONSTRAINT "device_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cameras" ADD CONSTRAINT "cameras_nanny_user_id_fkey" FOREIGN KEY ("nanny_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS "users_firebase_uid_key" ON "users"("firebase_uid");
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX IF NOT EXISTS "users_phone_key" ON "users"("phone");
CREATE INDEX IF NOT EXISTS "users_role_idx" ON "users"("role");
CREATE INDEX IF NOT EXISTS "users_deleted_at_idx" ON "users"("deleted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "nanny_profiles_user_id_key" ON "nanny_profiles"("user_id");
CREATE INDEX IF NOT EXISTS "nanny_profiles_availability_type_idx" ON "nanny_profiles"("availability_type");
CREATE INDEX IF NOT EXISTS "nanny_profiles_rating_idx" ON "nanny_profiles"("rating");
CREATE INDEX IF NOT EXISTS "nanny_profiles_approval_status_idx" ON "nanny_profiles"("approval_status");
CREATE UNIQUE INDEX IF NOT EXISTS "skills_name_key" ON "skills"("name");
CREATE INDEX IF NOT EXISTS "skills_deleted_at_idx" ON "skills"("deleted_at");
CREATE INDEX IF NOT EXISTS "nanny_skills_nanny_profile_id_idx" ON "nanny_skills"("nanny_profile_id");
CREATE INDEX IF NOT EXISTS "nanny_skills_skill_id_idx" ON "nanny_skills"("skill_id");
CREATE UNIQUE INDEX IF NOT EXISTS "nanny_skills_nanny_profile_id_skill_id_key" ON "nanny_skills"("nanny_profile_id", "skill_id");
CREATE UNIQUE INDEX IF NOT EXISTS "app_settings_key_key" ON "app_settings"("key");
CREATE INDEX IF NOT EXISTS "duration_multiplier_rules_is_active_idx" ON "duration_multiplier_rules"("is_active");
CREATE INDEX IF NOT EXISTS "duration_multiplier_rules_deleted_at_idx" ON "duration_multiplier_rules"("deleted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "promo_codes_code_key" ON "promo_codes"("code");
CREATE INDEX IF NOT EXISTS "promo_codes_is_active_idx" ON "promo_codes"("is_active");
CREATE INDEX IF NOT EXISTS "promo_codes_deleted_at_idx" ON "promo_codes"("deleted_at");
CREATE INDEX IF NOT EXISTS "promo_code_redemptions_promo_code_id_user_id_idx" ON "promo_code_redemptions"("promo_code_id", "user_id");
CREATE INDEX IF NOT EXISTS "promo_code_redemptions_user_id_idx" ON "promo_code_redemptions"("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "reward_wallets_user_id_key" ON "reward_wallets"("user_id");
CREATE INDEX IF NOT EXISTS "reward_ledger_entries_user_id_created_at_idx" ON "reward_ledger_entries"("user_id", "created_at");
CREATE INDEX IF NOT EXISTS "reward_ledger_entries_booking_id_idx" ON "reward_ledger_entries"("booking_id");
CREATE INDEX IF NOT EXISTS "bookings_mother_id_idx" ON "bookings"("mother_id");
CREATE INDEX IF NOT EXISTS "bookings_nanny_profile_id_idx" ON "bookings"("nanny_profile_id");
CREATE INDEX IF NOT EXISTS "bookings_status_idx" ON "bookings"("status");
CREATE INDEX IF NOT EXISTS "bookings_nanny_decision_idx" ON "bookings"("nanny_decision");
CREATE INDEX IF NOT EXISTS "bookings_date_idx" ON "bookings"("date");
CREATE INDEX IF NOT EXISTS "bookings_promo_code_id_idx" ON "bookings"("promo_code_id");
CREATE UNIQUE INDEX IF NOT EXISTS "payments_booking_id_key" ON "payments"("booking_id");
CREATE INDEX IF NOT EXISTS "payments_paymob_order_id_idx" ON "payments"("paymob_order_id");
CREATE INDEX IF NOT EXISTS "payments_paymob_next_reconcile_at_idx" ON "payments"("paymob_next_reconcile_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reviews_booking_id_key" ON "reviews"("booking_id");
CREATE INDEX IF NOT EXISTS "reviews_nanny_profile_id_idx" ON "reviews"("nanny_profile_id");
CREATE INDEX IF NOT EXISTS "reviews_mother_id_idx" ON "reviews"("mother_id");
CREATE INDEX IF NOT EXISTS "care_logs_booking_id_idx" ON "care_logs"("booking_id");
CREATE INDEX IF NOT EXISTS "care_logs_nanny_profile_id_idx" ON "care_logs"("nanny_profile_id");
CREATE INDEX IF NOT EXISTS "care_logs_occurred_at_idx" ON "care_logs"("occurred_at");
CREATE INDEX IF NOT EXISTS "community_posts_type_created_at_idx" ON "community_posts"("type", "created_at");
CREATE INDEX IF NOT EXISTS "community_posts_author_id_created_at_idx" ON "community_posts"("author_id", "created_at");
CREATE INDEX IF NOT EXISTS "post_likes_post_id_idx" ON "post_likes"("post_id");
CREATE INDEX IF NOT EXISTS "post_likes_user_id_idx" ON "post_likes"("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "post_likes_post_id_user_id_key" ON "post_likes"("post_id", "user_id");
CREATE INDEX IF NOT EXISTS "comments_post_id_created_at_idx" ON "comments"("post_id", "created_at");
CREATE INDEX IF NOT EXISTS "comments_author_id_idx" ON "comments"("author_id");
CREATE INDEX IF NOT EXISTS "comments_parent_comment_id_idx" ON "comments"("parent_comment_id");
CREATE INDEX IF NOT EXISTS "comment_likes_comment_id_idx" ON "comment_likes"("comment_id");
CREATE INDEX IF NOT EXISTS "comment_likes_user_id_idx" ON "comment_likes"("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "comment_likes_comment_id_user_id_key" ON "comment_likes"("comment_id", "user_id");
CREATE INDEX IF NOT EXISTS "event_rsvps_post_id_idx" ON "event_rsvps"("post_id");
CREATE INDEX IF NOT EXISTS "event_rsvps_user_id_idx" ON "event_rsvps"("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "event_rsvps_post_id_user_id_key" ON "event_rsvps"("post_id", "user_id");
CREATE INDEX IF NOT EXISTS "conversations_community_post_id_idx" ON "conversations"("community_post_id");
CREATE INDEX IF NOT EXISTS "conversations_initiator_id_idx" ON "conversations"("initiator_id");
CREATE UNIQUE INDEX IF NOT EXISTS "conversations_community_post_id_initiator_id_key" ON "conversations"("community_post_id", "initiator_id");
CREATE INDEX IF NOT EXISTS "conversation_participants_user_id_idx" ON "conversation_participants"("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "conversation_participants_conversation_id_user_id_key" ON "conversation_participants"("conversation_id", "user_id");
CREATE INDEX IF NOT EXISTS "messages_conversation_id_created_at_idx" ON "messages"("conversation_id", "created_at");
CREATE INDEX IF NOT EXISTS "messages_sender_id_idx" ON "messages"("sender_id");
CREATE INDEX IF NOT EXISTS "notifications_user_id_is_read_created_at_idx" ON "notifications"("user_id", "is_read", "created_at");
CREATE INDEX IF NOT EXISTS "notifications_user_id_type_idx" ON "notifications"("user_id", "type");
CREATE UNIQUE INDEX IF NOT EXISTS "device_tokens_token_key" ON "device_tokens"("token");
CREATE INDEX IF NOT EXISTS "device_tokens_user_id_idx" ON "device_tokens"("user_id");
CREATE INDEX IF NOT EXISTS "cameras_nanny_user_id_idx" ON "cameras"("nanny_user_id");
CREATE INDEX IF NOT EXISTS "cameras_deleted_at_idx" ON "cameras"("deleted_at");
