import { StyleSheet } from 'react-native';
import {
  colors,
  fontFamily,
  typeScale,
  spacing,
  borderRadius,
  screenPadding,
  shadows,
  STATUS_BAR_HEIGHT,
  HEADER_HEIGHT,
} from '@mobile/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: HEADER_HEIGHT + spacing.lg,
    paddingBottom: spacing['4xl'],
    paddingHorizontal: screenPadding,
    gap: spacing['2xl'],
  },
  tag: {
    ...typeScale.labelSm,
    fontFamily: fontFamily.bold,
    letterSpacing: 1.2,
    color: colors.goldWarm,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  title: {
    ...typeScale.headingLg,
    color: colors.textPrimary,
    textAlign: 'center',
    lineHeight: 32,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  metaText: {
    ...typeScale.bodySm,
    color: colors.textMuted,
  },
  metaDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.textMuted,
  },
  introCard: {
    backgroundColor: colors.taupeLight,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    gap: spacing.sm,
  },
  introText: {
    ...typeScale.bodyMd,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  sectionLabel: {
    ...typeScale.labelMd,
    fontFamily: fontFamily.semiBold,
    color: colors.textPrimary,
  },
  questionCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    gap: spacing.md,
    ...shadows.sm,
  },
  questionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  questionNumber: {
    width: 32,
    height: 32,
    borderRadius: borderRadius.full,
    backgroundColor: colors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  questionNumberText: {
    ...typeScale.labelMd,
    fontFamily: fontFamily.bold,
    color: colors.primaryDark,
  },
  questionText: {
    ...typeScale.headingSm,
    flex: 1,
    color: colors.textPrimary,
    lineHeight: 24,
  },
  blockLabel: {
    ...typeScale.labelSm,
    fontFamily: fontFamily.bold,
    color: colors.primaryDark,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  blockText: {
    ...typeScale.bodyMd,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  tipCard: {
    backgroundColor: colors.primaryMuted,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    gap: spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  tipTitle: {
    ...typeScale.labelMd,
    fontFamily: fontFamily.bold,
    color: colors.primaryDark,
  },
  tipBody: {
    ...typeScale.bodyMd,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  ctaButton: {
    backgroundColor: colors.primaryDark,
    borderRadius: borderRadius.full,
    paddingVertical: spacing.lg,
    alignItems: 'center',
    ...shadows.sm,
  },
  ctaButtonText: {
    ...typeScale.labelMd,
    fontFamily: fontFamily.bold,
    color: colors.white,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: STATUS_BAR_HEIGHT + spacing.sm,
    paddingHorizontal: screenPadding,
    zIndex: 100,
  },
  backBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
