// Vercel serverless function entry. This file is committed to git so Vercel's
// function detection registers a Serverless Function on Git-triggered deploys.
// The heavy Express bundle is generated by esbuild at build time (see
// esbuild.config.mjs) and written to ../dist/vercel-bundle.cjs, which stays
// gitignored. All routes are rewritten to this function via vercel.json.
module.exports = require('../dist/vercel-bundle.cjs');
